### ISSUE TITLE
Creative menu icon spacing is completely buggered and doesn't line up with the bg image

### ISSUE THREAD

**Issue by iownall555** [Avamander/MineFix#42]
It would seem as the spacing between the items in the creative menu doesn't line up with the background images as can be seen in [these images](https://imgur.com/a/g6ARQ).

If it matters, I'm using Minetest 0.4.14-dev on a laptop with a screen res of 1366x768.

**Comment by PureTryOut** [comment]
Known issue. I believe @whitephoenix0 is going to fix this. Basically enholds editing the background to fit the dimensions.

**Comment by PureTryOut** [comment]
Fixed by #44
